controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_cont:
      type: diff_drive_controller/DiffDriveController

joint_broad:
  ros__parameters: {}

diff_cont:
  ros__parameters:
    # Wheel Joint Names
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    # Physical Parameters - CRITICAL: Đúng kích thước từ URDF
    wheel_separation: 0.322  # m - distance between wheels
    wheel_radius: 0.05       # m - wheel radius

    # TF and Odometry Settings
    publish_odom: true
    odom_frame_id: "odom"
    base_frame_id: "base_footprint"
    enable_odom_tf: true

    # CRITICAL: Accept unstamped cmd_vel
    cmd_vel_timeout: 0.5
    publish_rate: 50.0
    
    # Input/Output remapping
    cmd_vel: cmd_vel  # Subscribe to standard /cmd_vel topic
    
    # Velocity Limits - Tăng giới hạn để robot chạy nhanh hơn
    linear.x.has_velocity_limits: true
    linear.x.max_velocity: 2.0   # Tăng từ 0.5 lên 2.0
    linear.x.min_velocity: -2.0
    angular.z.has_velocity_limits: true
    angular.z.max_velocity: 2.0  # Tăng từ 1.0 lên 2.0
    angular.z.min_velocity: -2.0

    # Covariance
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]